# Use postgres/example user/password credentials
version: "3.1"
services:
  db:
    image: postgres:11
    restart: always
    networks:
      numbas-net:
        aliases:
          - postgres
    volumes:
      - ./data/postgres-passport:/docker-entrypoint-initdb.d
      - ./data/postgres_passport_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password

  numbas:
    image: numbas
    restart: always
    networks:
      - numbas-net
    ports:
      - 7784:80
    volumes:
      - data/numbas:/srv/numbas
    environment:
      ADMIN_USERNAME: admin
      ADMIN_EMAIL: admin@learnhopper.de
    entrypoint: /entrypoint.sh
    secrets:
      - numbas_editor
      - postgres_password
      - numbas_admin_password

networks:
  numbas-net:

secrets:
  numbas_editor:
    file: ./numbas_editor
  numbas_admin_password:
    file: ./numbas_admin_password
  postgres_password:
    file: ./postgres_password
