# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:11
    restart: always
    networks:
      numbas-net:
        aliases:
          - postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password

  numbas:
    image: numbas
    restart: always
    networks:
      - numbas-net
    ports:
      - 8080:80
    environment:
      ADMIN_USERNAME: admin
      ADMIN_EMAIL: admin@admin.com
    entrypoint: /entrypoint.sh
    secrets:
      - numbas_editor
      - postgres_password
      - numbas_admin_password

volumes:
  pgdata:

networks:
  numbas-net:

secrets:
  numbas_editor:
    external: true
  numbas_admin_password:
    external: true
  postgres_password:
    external: true
